#!/usr/bin/env bash
# Self-heal the published footprint claims. Run by the footprint-heal job in
# .github/workflows/ci.yml, only after `footprint.py evaluate` found that a fresh
# measurement of main makes at least one published claim untrue.
#
#   scripts/footprint-heal.sh <fresh.json> <report.md>
#
# 1. adopt the measurement and regenerate every claim (footprint.py adopt)
# 2. re-run the docs gate on the result; a heal that fails its own gate stops here
# 3. force-push the result to ONE branch (footprint/refresh), so a stale refresh is
#    replaced rather than a second one opened
# 4. open a PR for it, then dispatch CI on the branch: pushes made with
#    GITHUB_TOKEN do not trigger workflows, but workflow_dispatch does, and its
#    check runs attach to the branch head, satisfying the required checks
# 5. if the repo does not let Actions open PRs (Settings > Actions > General >
#    "Allow GitHub Actions to create and approve pull requests"), open or update
#    ONE issue with a one-click compare link instead. The heal is never lost.
set -euo pipefail
FRESH="$1"
REPORT="$2"
BRANCH="${FOOTPRINT_HEAL_BRANCH:-footprint/refresh}"
REPO="${GITHUB_REPOSITORY:?}"
SHA="${GITHUB_SHA:?}"
TITLE="docs(perf): refresh footprint claims from a new measurement"
ISSUE_TITLE="Footprint claims need a refresh"

python3 scripts/footprint.py adopt "$FRESH"
python3 scripts/footprint.py check

if git diff --quiet; then
    echo "footprint-heal: adopting the measurement changed nothing; a refresh already landed."
    exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git checkout -B "$BRANCH"
git add -u
{
    echo "docs(perf): refresh footprint claims from main@${SHA:0:9}"
    echo
    echo "Generated by the footprint-heal job (scripts/footprint-heal.sh)."
    echo
    cat "$REPORT"
} > "$RUNNER_TEMP/commit-msg"
git commit -q -F "$RUNNER_TEMP/commit-msg"
git push -f origin "$BRANCH"

BODY="$RUNNER_TEMP/body.md"
{
    cat "$REPORT"
    echo
    echo "Every file in this PR was regenerated by \`scripts/footprint.py adopt\` from the measurement"
    echo "the \`release-size\` job took of main@${SHA:0:9}; review the numbers, not the prose."
    echo "Budgets and the refresh tolerance live in \`docs/perf/footprint-budget.json\`."
    echo
    echo "🤖 Opened by the footprint-heal job."
} > "$BODY"

pr="$(gh pr list --repo "$REPO" --head "$BRANCH" --state open --json number --jq '.[0].number // empty')"
if [ -z "$pr" ]; then
    if url="$(gh pr create --repo "$REPO" --base main --head "$BRANCH" --title "$TITLE" --body-file "$BODY" 2>"$RUNNER_TEMP/pr.err")"; then
        pr="${url##*/}"
        echo "footprint-heal: opened $url"
    else
        echo "footprint-heal: could not open a PR ($(tr '\n' ' ' < "$RUNNER_TEMP/pr.err")); falling back to an issue."
    fi
else
    echo "footprint-heal: updated the existing PR #$pr"
fi

if [ -n "$pr" ]; then
    gh workflow run ci.yml --repo "$REPO" --ref "$BRANCH" \
        || echo "::warning::could not dispatch CI on $BRANCH; re-run it from the PR to satisfy required checks."
    exit 0
fi

compare="${GITHUB_SERVER_URL:-https://github.com}/$REPO/compare/main...$BRANCH?expand=1"
{
    cat "$REPORT"
    echo
    echo "The regenerated docs are on \`$BRANCH\`. **[Open the PR in one click]($compare).**"
    echo
    echo "This is an issue rather than a PR because Actions may not open PRs in this repo."
    echo "Allowing it (Settings > Actions > General > Workflow permissions) makes the refresh fully automatic."
} > "$BODY"
issue="$(gh issue list --repo "$REPO" --state open --search "in:title \"$ISSUE_TITLE\"" --json number --jq '.[0].number // empty')"
if [ -n "$issue" ]; then
    gh issue comment "$issue" --repo "$REPO" --body-file "$BODY"
    echo "footprint-heal: updated issue #$issue"
else
    gh issue create --repo "$REPO" --title "$ISSUE_TITLE" --body-file "$BODY"
fi
