# GenGitSha.cmake — stamp the current git HEAD into a generated header.
#
# Run at BUILD time (not configure time) via the hu_git_sha_stamp custom
# target, so incremental rebuilds after new commits pick up the fresh SHA
# without a reconfigure. Deploy provenance depends on this: the installer
# (scripts/install-human-daemon.sh) compares the SHA embedded in a candidate
# binary against the installed one and refuses non-descendant installs.
#
# Inputs:  -DGIT_DIR=<repo root>  -DOUT=<path to hu_git_sha.h>
# The header is rewritten only when the SHA changes, so no-op builds do not
# relink version.c.o / the executables.

execute_process(
    COMMAND git -C "${GIT_DIR}" rev-parse HEAD
    OUTPUT_VARIABLE HU_SHA
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE HU_SHA_RC)

if(NOT HU_SHA_RC EQUAL 0 OR NOT HU_SHA MATCHES "^[0-9a-f]+$")
    # Not a git checkout (tarball build, shallow CI oddity): advisory value.
    set(HU_SHA "unknown")
endif()

set(HU_CONTENT "/* generated by cmake/GenGitSha.cmake — do not edit */\n#define HU_GIT_SHA \"${HU_SHA}\"\n")

set(HU_OLD "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" HU_OLD)
endif()

if(NOT HU_OLD STREQUAL HU_CONTENT)
    file(WRITE "${OUT}" "${HU_CONTENT}")
endif()
